GET http://localhost:3000/users 

###
GET http://localhost:3000/users/650653bfc0e85d4f15dbd48f

###
POST http://localhost:3000/users
content-type: application/json

{
    "First_name": "Johnny",
    "Last_name": "Danger",
    "Email": "DrDeathDefying@Explosion.com",
    "Favorite_color": "Red",
    "Birthday" : "1-1-2000"
}

###
PUT http://localhost:3000/users/650653bfc0e85d4f15dbd48f HTTP/1.1
content-type: application/json

{
    "First_name": "BendtJ",
    "Last_name": "Dahl",
    "Email": "WriteBendt24@gmail.com",
    "Favorite_color": "Green",
    "Birthday" : "5-26-1999"
}